/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.Doctor;
import Clases.MapaCiudades;
import Clases.ListaDoctores;
import Clases.ListaHospitales;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diego
 */
public class MostrarDoctor extends javax.swing.JFrame {

    /**
     * Creates new form MostrarDoctor
     */
    public MostrarDoctor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public static String rutDoctorBuscado = "";
    private static Doctor DoctorBuscado;

    public static Doctor getDoctorBuscado() {
        return DoctorBuscado;
    }

    public static void setDoctorBuscado(Doctor DoctorBuscado) {
        MostrarDoctor.DoctorBuscado = DoctorBuscado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctores = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setText("REPORTE TXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("VOLVER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("SALIR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        doctores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        doctores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(doctores);

        jButton2.setText("CONTACTAR DOCTOR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(4, 4, 4)
                        .addComponent(jButton5))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String cod = ElegirCiudad.codCiudad;
        String codHospital = ElegirHospital.rolHospital;

        FileWriter w = null;
        try {
            ListaDoctores LD = MenuPrincipal.SH.getCiudades().getCiudad(cod).getHospitales().getHospital(codHospital).getDoctores();
            File f;
            f = new File("Doctores del hospital " + MenuPrincipal.SH.getCiudades().getCiudad(cod).getHospitales().getHospital(codHospital).getNombre() + ".txt");
            w = new FileWriter(f);
            BufferedWriter bw = new BufferedWriter(w);
            for (int i = 0; i < LD.cantidadDoctores(); i++) {

                try {

                    bw.write("NOMBRE: " + LD.getDoctor(i).getNombre());
                    bw.newLine();
                    bw.write("RUT: " + LD.getDoctor(i).getRut());
                    bw.newLine();
                    bw.write("CONTACTO: " + LD.getDoctor(i).getContacto());
                    bw.newLine();
                    bw.write("ESPECIALIDAD " + LD.getDoctor(i).getEspecialidad());
                    bw.newLine();
                    bw.write("SALA DE ATENCION: " + LD.getDoctor(i).getSalaAtencion());
                    bw.newLine();
                    bw.newLine();
                } catch (IOException e) {
                };

            }
            bw.close();

            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(MostrarCiudades.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                w.close();
            } catch (IOException ex) {
                Logger.getLogger(MostrarCiudades.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        MenuDoctores MD = new MenuDoctores();
        MD.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        DefaultTableModel modelo = (DefaultTableModel) doctores.getModel();
        String cod = ElegirCiudad.codCiudad;
        String codHospital = ElegirHospital.rolHospital;
        MapaCiudades LC = MenuPrincipal.SH.getCiudades();
        ListaHospitales LH = MenuPrincipal.SH.getCiudades().getCiudad(cod).getHospitales();

        modelo.addColumn("RUT");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("CONTACTO");
        modelo.addColumn("ESPECIALIDAD");
        modelo.addColumn("SALA DE ATENCION");
        for (int z = 0; z < LC.cantidadCiudades(); z++) {
            for (int j = 0; j < LC.getCiudad(z).getHospitales().cantidadHospitales(); j++) {
                for (int i = 0; i < LC.getCiudad(z).getHospitales().getHospital(j).getDoctores().cantidadDoctores(); i++) {
                    
                    Object row[] = {LC.getCiudad(z).getHospitales().getHospital(j).getDoctores().getDoctor(i).getRut(), LC.getCiudad(z).getHospitales().getHospital(j).getDoctores().getDoctor(i).getNombre(), LC.getCiudad(z).getHospitales().getHospital(j).getDoctores().getDoctor(i).getContacto(), LC.getCiudad(z).getHospitales().getHospital(j).getDoctores().getDoctor(i).getEspecialidad(), LC.getCiudad(z).getHospitales().getHospital(j).getDoctores().getDoctor(i).getSalaAtencion()};
                    System.out.println(LC.getCiudad(z).getHospitales().getHospital(j).getDoctores().getDoctor(i).getNombre());
                    ((DefaultTableModel) doctores.getModel()).addRow(row);
                }
            }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void doctoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctoresMouseClicked

        DefaultTableModel modelo = (DefaultTableModel) doctores.getModel();
        int selectedRowIndex = doctores.getSelectedRow();

        MapaCiudades LC = MenuPrincipal.SH.getCiudades();

        for (int z = 0; z < LC.cantidadCiudades(); z++) {
            for (int j = 0; j < LC.getCiudad(z).getHospitales().cantidadHospitales(); j++) {
                for (int i = 0; i < LC.getCiudad(z).getHospitales().getHospital(j).getDoctores().cantidadDoctores(); i++) {
                    if (LC.getCiudad(z).getHospitales().getHospital(j).getDoctores().getDoctor(i).getRut().equals(rutDoctorBuscado)) {
                        ElegirCiudad.codCiudad = LC.getCiudad(z).getCodigoPostal();
                        System.out.println(ElegirCiudad.codCiudad);
                        ElegirHospital.rolHospital = LC.getCiudad(z).getHospitales().getHospital(j).getNumeroRol();
                        System.out.println(ElegirHospital.rolHospital);
                    }
                }
            }
        }

        rutDoctorBuscado = modelo.getValueAt(selectedRowIndex, 0).toString();
        System.out.println(rutDoctorBuscado);
// TODO add your handling code here:
    }//GEN-LAST:event_doctoresMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String cod = ElegirCiudad.codCiudad;
        String codHospital = ElegirHospital.rolHospital;

        System.out.println(rutDoctorBuscado);
        Doctor D = new Doctor();
        System.out.println(ElegirCiudad.codCiudad);
                        
                        System.out.println(ElegirHospital.rolHospital);
        if (MenuPrincipal.SH.getCiudades().getCiudad(cod).getHospitales().getHospital(codHospital).getDoctores().existeDoctor(rutDoctorBuscado)) {
            D = MenuPrincipal.SH.getCiudades().getCiudad(cod).getHospitales().getHospital(codHospital).getDoctores().getDoctor(rutDoctorBuscado);
            DoctorBuscado = D;
            D.contactarPersona();
        } else {

            JOptionPane.showMessageDialog(null, "DOCTOR NO REGISTRADO EN EL SISTEMA.REALICE LA REVISION PERTINENTE A LOS DATOS DEL DOCTOR");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable doctores;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
